#ENC[AES256_GCM,data:tl5O56zH8fITKup4Ocot9dkLUBm2ryZaz7V1i/SvVygwX20pIQ==,iv:hovYZ4qsp0PCiSeNoXjTrR/wsHZyUlPS7zI9xjaORX0=,tag:J7z1xZ8YelXU5bVWGelj6w==,type:comment]
secrets:
    FOO: ENC[AES256_GCM,data:La0uA2zN+sTW2n7eVZflMxYgE0bLtSDk/vu0H2a3,iv:WsThhakmJZ6SQpCY2FwKIILzJyd8M9ABDbyqgeP7iaM=,tag:yMqSudDcbQqkC3+HQDdBJg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15rkke56gszzxrjrm3a52lgakepz83pkhv8vfa35y3lxxx9r0pf8qlw2qc2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5dWlEa1NwUUg5dnh3anM5
            N2pvT2lNMGpBVWw1VWdKQk51UVV1b1NYajBjCms4V2ZtS1pQTnNITi9FMFRDZm43
            cHZyTUxjZWovYTAvVGFTaENmdVc1N3MKLS0tIGRXcC9HNU8yMStpcHNkNGFDWGw4
            OE0rZUJVWVBDL0tmWGlwcDBEd05NN0EKhMYkhie3ZZwKCFBp0k9FxjhJ5mQOAGi8
            BN+5A8CEmmDFfzbFkAwjaXXJ1qpDNLmtOvubL6y4djxc27gu3416CA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-27T13:52:23Z"
    mac: ENC[AES256_GCM,data:8vp7PSmenyAAraGVPi0AnddyXv7SByNoIUP079tAQlJ8hEDuATCQJ0rPo4NMUxqDN/il2hkz0PxU/bti6mZgCazHL0MgmcZZkK+l7gjSn59QY9kPXvSmLAw9eyURcUHb8Pgv9Ur/Wf5s4vqmhXWyyXGJSNlOpA55evAgG2aG1QE=,iv:t1yAkaDMsUZLW98zu+LhfdSGbOuqmh49FKWdW38p200=,tag:sRgZLZ3asMU4qkk5/1qihg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.2
