apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: streamie-socket
  annotations:
    kubernetes.io/ingress.class: traefik
    # traefik.ingress.kubernetes.io/router.tls: "true"
    # traefik.ingress.kubernetes.io/router.entrypoints: https
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
    - hosts:
        - streamie-socket.narze.live
      secretName: streamie-socket-tls
  rules:
    - host: streamie-socket.narze.live
      http:
        paths:
          - backend:
              service:
                name: streamie-socket
                port:
                  number: 8888
            path: /
            pathType: Prefix
