secrets:
    CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:2yiHhF3aZ27mymQdFKgBF3Y3QFIU2p+rKxhUn4NmH9Xg+aHrCLE/FA==,iv:233pjdIs1AIckYU/6dYHBLO+zxe+4YouoJxVA+iulFU=,tag:Nx2dNmsOO8wF6Sp9pMtb9w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15rkke56gszzxrjrm3a52lgakepz83pkhv8vfa35y3lxxx9r0pf8qlw2qc2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoUFY3bVFQWFZNNlVDOEY3
            elJ6MGhGNkJROXhVYnV1UHpYaXNOSVlidUJBCmQ1bXI3ZzZRdWhpcStnUTlUa0V3
            cStabEs4VmovT1k3VGFrY0N3bURLT0EKLS0tIFBKWmJkV3lFQW9qWXpVNEtNZUQ4
            NVJOUVU2TU83aUZNbCs4NzNrSXJMRWcKiDEAC3NojYtdkRtW0j3TKvUQulTGPdn0
            YY7X7pZjeMhhHw5I673Wxo7VhoCJqXfvonLpbuHm5+3tSef05cFdQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-17T17:38:09Z"
    mac: ENC[AES256_GCM,data:GIEGx7Ov3yyA5Tm/eqPZH003rhUABRfMoXzMwe5L5QO8jBsmqFNx8FVugSZCkzBpYDjDDcmvGDz9xNgvsfSe/lL6phXRwygKp21acrtmPpUdhMRzg8FiELlw3G1eWchQSBxjoyukCcBRUxs0U3VGaqU5yc6kOxuunKaMl5Ze+So=,iv:WxsbxEIGszxONTsHlxclSTAPdXQ85OnS9RbFq12zMeo=,tag:G9yIzxH92C6C7J/pJXBaAw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.2
