#ENC[AES256_GCM,data:N5ajr80QtoIoov9MG7QTtsvUT4dErhpsbm9mKf0pMuKFgO6okA==,iv:1JDVA+2yaMR9efvDtRTrWH8/D5AzUizfmB5lBecBP7A=,tag:U6GlvF3C5d9Yv9iUdTOTVQ==,type:comment]
secrets:
    DEV_GUILD_ID: ENC[AES256_GCM,data:pMIQyU+f0iUZieo28a+Knb79,iv:tjrjGzFulunyEQ3ed/cdc3foft36mnN91UIRxknOiuQ=,tag:givX9fUxSHxm7xLWQ899mQ==,type:str]
    DISCORD_TOKEN: ENC[AES256_GCM,data:E+OFFUXm1L5Qm7fqTANCd/4+IqK9JE09pCJzaXrUn/2gi5tEZkXVTpdqEnKx1AkeFoqmv7t2vRJyaPs=,iv:RpDxQ9w8nAXF8fgYdJe1xfg6ntm5xrZGL9onSoEfVE4=,tag:09aMJsGdlp+/QLqypzbpfg==,type:str]
    OAUTH_CLIENT_ID: ENC[AES256_GCM,data:ov0xNZpyyVtkj3myP8s+ou6Q,iv:Jy1LmPXi5KEEEwRUbEklm7+oKZSAZkmt4fDqjIqv3JI=,tag:YNdt//EeOS+0/5vcZgRkLg==,type:str]
    TWITCH_OAUTH_TOKEN: ENC[AES256_GCM,data:CUbCNbot/Zdk5of+v3UPlMCHK0dP2y62Pw3gHF8iJVlweUOS,iv:YkeUhBjmGsayU93vyVpA9BK6FwfJLzKAuwKCTxyyilA=,tag:+iJ9KUN3Axpn5+Rt8TnqOQ==,type:str]
    DISCORD_ADMIN_USER_ID: ENC[AES256_GCM,data:vHlkQintrCLbRho15GGGKyPO,iv:DogIcotmILg5ZglGhHcsjsUf/ElO7QgShniQ6Z08tg8=,tag:h3IWMk77tpUCbuxStUdEvw==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:BnUqAKEPwCw9AYOwuS0nMX/EbwIv276CSvajAaSNpM5ZWCeYMZYaZlSItntUgfCPYzbltR41tiUamft8udTsjjqVFQTPfUP+FTQjvh7vSO1xQn431JVElEImZkZuOS2lMgb0kP+PpEkogTQIeNjDBdyeSBdpxJ9s9H3Yt8mMfpLdwCDdFelerl5QS6qbzO0h1Llgsse2CPzFNMtmCMZ4Glg=,iv:N5atn7xSXpoo2cllBMGD4bl5S1Q3anb0IYohb4Fg91o=,tag:hLw39dJiOaoqfAsNhx6wlw==,type:str]
    TWITCH_HELIX_OAUTH_TOKEN: ENC[AES256_GCM,data:Ha/0t36Ovrx8djLkbQZgatkAokjuKUdE/42imVVd,iv:I2sHgGZGk4wZzNAqWftA+nujpKmcKtmC/Xl7fYp7FxE=,tag:QO6Fa4+R5nC8E+CHm5pBZg==,type:str]
    TWITCH_HELIX_CLIENT_ID: ENC[AES256_GCM,data:ZvcdQo2yc9hQQ4+Og0VqPZAHo9Mh5MAGNMDITwPD,iv:BW/lplMdR8GBxkj0LRj7EizJqsMkJuTqH39RNNkvDx8=,tag:I3SgIK5dLK9wsiSQ/AAAyQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15rkke56gszzxrjrm3a52lgakepz83pkhv8vfa35y3lxxx9r0pf8qlw2qc2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4RG9ES0tmMmRQY1ZiR1lE
            MWh4TE5RZjUrRGJSRlZpK0J1aW11SE1ReFFVCno1UDNqME5mQ0FrR2l4bkVHQlA0
            a21wUWI5VEg1ZWJ0QUdUd0VCWkl3SWsKLS0tIHJUUmVGYWs2dU43dXJWUmJuN3Iw
            eEFtd28zeDdrOUZDN3JkZ0FlamZLQlkKZ2JMStgF9bpoz68PTtU30JHbGcJNxP5l
            H8cUxA6zCgRa/5ejv9g3ewAjtQ3KC0iE9sk/MqyS1B+VOjtneBgn6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-04-08T18:17:28Z"
    mac: ENC[AES256_GCM,data:5f9NQQuFnMpvEuo7cW2uS0kMQgnHy/3oTa+C2LFwJqq4awcSDXjiUASbMfz/SoALFm8M33BFyGLTVzMNUg+empuXrnqgnJisR59btdDT0Cjp6cKlRZ2xFXJSRUf7vahzqU9gXzidXZzBw0h4hpykQPUbUPko1jnN5fCXq/dqlRM=,iv:BhqCM8OKDH3zHne7hKpR4O8rj9e6DngDIYFrGsvDOiY=,tag:9byTTNZSy9UD6/jfryiSBQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.2
