apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  # annotations:
  #   argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: streamie
    server: "{{ .Values.spec.destination.server }}"
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: redis
    targetRevision: 16.8.5
    helm:
      values: |
        auth:
          enabled: false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
