apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 80
  selector:
    app: nginx-sample-kustomize
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx-sample-kustomize
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-sample-kustomize
  template:
    metadata:
      labels:
        app: nginx-sample-kustomize
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
