apiVersion: ENC[AES256_GCM,data:Fus=,iv:DnIX+H/T0UhyMX8fY4TgqfPJetoo4e00X6Aqy8FC5U8=,tag:aT0XA+/rEZ1BsB8zOC3J0g==,type:str]
kind: ENC[AES256_GCM,data:IYhGHV7f,iv:n2BM2r0acEGbSHoxbc5cU0MzHRKZ9YtWugUpYWvtQ54=,tag:6ODRKlCGz8Y3KHJ8i0Kelw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:6ZXgLcdk15cLGBusYfKqS7S2psq6JJI=,iv:CvMimJx5wDnEdiC7sbSwyp/9nq28vXB3oe3O5ymVhes=,tag:VBrPIL+nme+AHjVpZab9mA==,type:str]
type: ENC[AES256_GCM,data:9KbH/mjr,iv:1aNXLL5iaGuT71N28pWLBPc59P/yN2L7h0Or+jTNxN0=,tag:q76bFlKWwMnxQSKgh38WJQ==,type:str]
data:
    username: ENC[AES256_GCM,data:kcOukwIz0Ao8T0Gt,iv:kcw1AJLmjx95kiQ7Jher4AXFQWPxVGGMCJKjyPe/FUg=,tag:ikpmxGcMKsrRiFWfgN1MmA==,type:str]
    password: ENC[AES256_GCM,data:2CkjvFlgAdAhYHCp,iv:2AALo06jGrhu7utJGh7jkUAZX/4bShqDFve108jEp9k=,tag:70p/nagrwwJv6+hk4GQTQQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15rkke56gszzxrjrm3a52lgakepz83pkhv8vfa35y3lxxx9r0pf8qlw2qc2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWdERaeVBhNWdDWFM3aExD
            VXZjOWdBaktBTU1ZUDdKZVBuNVBkNjNrc3pjCkxHU0tJTGlyOUdEM21iWmdWWnZn
            b3ZzSEJyOWpiSGFhRU1EM3lMT2lqR0UKLS0tIDBHb3Z6c0gwbHhhMFFsT21ZTyt1
            aDBTUUFRRXEvTGdFOTZUZTlrN25yV1EKAU5Qyc3FI2QttNV96C3qSnT5byS5Ti+M
            8hy/W4z/zrw3VpoNWHxs4L3w9OvlkNP7KNsJkQ0i2LCrn7ZKUgMkFw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-27T16:23:35Z"
    mac: ENC[AES256_GCM,data:I5Mkvw3PVXh2SQHHNZ4aki3W5s5Oi6Qy4+NlSjegTP+UJPiX5YpdZfNHBNiUy0CvrUFTw1jRgjPCwopMr6OuobtfPYIvX9ohDJ7s9xUuEJR0zqJMR00StJ1aaMy+J1g+hGK+lpCIjMCg+glhFo5Hiy1e3kM8LHbdan5X52gE+xo=,iv:mmPrvzMWNILJVJzavWKpb6J1QN2+zLUEup5robRB59U=,tag:vBSSt8xNV1OErwC0nxF0aA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.2
