apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: streamie-web
  name: streamie-web
spec:
  selector:
    matchLabels:
      app: streamie-web
  replicas: 1
  template:
    metadata:
      labels:
        app: streamie-web
    spec:
      containers:
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          name: streamie-web
          ports:
            - containerPort: 3000
          command: ["node"]
          args: ["."]
          workingDir: "/app/web/web"
