apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Chart.Name }}"
  labels:
    app: "{{ .Chart.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  DEV_GUILD_ID: "{{ .Values.secrets.DEV_GUILD_ID | b64enc }}"
  DISCORD_TOKEN: "{{ .Values.secrets.DISCORD_TOKEN | b64enc }}"
  OAUTH_CLIENT_ID: "{{ .Values.secrets.OAUTH_CLIENT_ID | b64enc }}"
  TWITCH_OAUTH_TOKEN: "{{ .Values.secrets.TWITCH_OAUTH_TOKEN | b64enc }}"
