apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Chart.Name }}"
  labels:
    app: "{{ .Chart.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  # TODO: Loop from secret-values
  DEV_GUILD_ID: "{{ .Values.secrets.DEV_GUILD_ID | toString | b64enc }}"
  DISCORD_TOKEN: "{{ .Values.secrets.DISCORD_TOKEN | toString | b64enc }}"
  OAUTH_CLIENT_ID: "{{ .Values.secrets.OAUTH_CLIENT_ID | toString | b64enc }}"
  TWITCH_OAUTH_TOKEN: "{{ .Values.secrets.TWITCH_OAUTH_TOKEN | toString | b64enc }}"
  DISCORD_ADMIN_USER_ID: "{{ .Values.secrets.DISCORD_ADMIN_USER_ID | toString | b64enc }}"
  DATABASE_URL: "{{ .Values.secrets.DATABASE_URL | toString | b64enc }}"
  TWITCH_HELIX_OAUTH_TOKEN: "{{ .Values.secrets.TWITCH_HELIX_OAUTH_TOKEN | toString | b64enc }}"
  TWITCH_HELIX_CLIENT_ID: "{{ .Values.secrets.TWITCH_HELIX_CLIENT_ID | toString | b64enc }}"
  # VITE_DISCORD_CLIENT_ID: "{{ .Values.secrets.VITE_DISCORD_CLIENT_ID | toString | b64enc }}"
  # VITE_DISCORD_CLIENT_SECRET: "{{ .Values.secrets.VITE_DISCORD_CLIENT_SECRET | toString | b64enc }}"
