apiVersion: v1
kind: Service
metadata:
  name: streamie
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: streamie
---
apiVersion: v1
kind: Service
metadata:
  name: streamie-web
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: streamie-web
---
apiVersion: v1
kind: Service
metadata:
  name: streamie-redis
spec:
  type: LoadBalancer
  # externalName: redis.streamie.homelab.narze.live
  ports:
    - port: 56379
      protocol: TCP
      targetPort: 6379
  # externalIPs:
  #   - 100.113.190.46
  externalName: redis.streamie.homelab.narze.live
  selector:
    app: streamie-redis
