# apiVersion: v1
# kind: Service
# metadata:
#   name: streamie
#   namespace: streamie
# spec:
#   ports:
#     - port: 80
#       protocol: TCP
#       targetPort: 3000
#   selector:
#     app: streamie
