argo-cd:
  dex:
    enabled: false
  server:
    extraArgs:
      - --insecure
    config:
      repositories: |
        - type: git
          name: home-cluster
          url: https://github.com/narze/home-cluster.git
        - type: helm
          name: argo-cd
          url: https://argoproj.github.io/argo-helm

      # helm-secrets (1/2)
      helm.valuesFileSchemes: >-
        secrets+gpg-import, secrets+gpg-import-kubernetes,
        secrets+age-import, secrets+age-import-kubernetes,
        secrets,
        https

    additionalApplications:
      # Self-managed ArgoCD
      - name: argo-cd
        namespace: argocd
        destination:
          namespace: argocd
          server: https://kubernetes.default.svc
        project: argocd
        source:
          path: charts/argo-cd
          # This repo
          repoURL: https://github.com/narze/home-cluster.git
          targetRevision: HEAD
        syncPolicy:
          automated:
            prune: true
            selfHeal: true
        #   syncOptions:
        #   - CreateNamespace=true

      # Root app of apps `/apps`
      - name: root
        namespace: argocd
        destination:
          namespace: argocd
          server: https://kubernetes.default.svc
        project: default
        source:
          path: apps
          repoURL: https://github.com/narze/home-cluster.git
          targetRevision: HEAD
        syncPolicy:
          automated:
            selfHeal: true
            prune: true

    additionalProjects:
      - name: argocd
        namespace: argocd
        additionalLabels: {}
        additionalAnnotations: {}
        description: ArgoCD Project
        sourceRepos:
          - "*"
        destinations:
          - namespace: argocd
            server: https://kubernetes.default.svc
        clusterResourceWhitelist:
          - group: "*"
            kind: "*"
        orphanedResources:
          warn: false

  # Replace ApplicationSet image with arm64 built one until official one is ready
  # Ref. https://github.com/argoproj/argo-cd/issues/8394
  applicationSet:
    image:
      # -- Repository to use for the application set controller
      repository: ghcr.io/jr64/argocd-applicationset
      # -- Image pull policy for the application set controller
      pullPolicy: IfNotPresent
      # -- Tag to use for the application set controller
      tag: "v0.4.0"

  # helm-secrets (2/2) start
  repoServer:
    env:
      - name: HELM_PLUGINS
        value: /custom-tools/helm-plugins/
      # In case wrapper scripts are used, HELM_SECRETS_HELM_PATH needs to be the path of the real helm binary
      - name: HELM_SECRETS_HELM_PATH
        value: /usr/local/bin/helm
      - name: HELM_SECRETS_SOPS_PATH
        value: /custom-tools/sops
      - name: HELM_SECRETS_KUBECTL_PATH
        value: /custom-tools/kubectl
      # https://github.com/jkroepke/helm-secrets/wiki/Security-in-shared-environments
      - name: HELM_SECRETS_VALUES_ALLOW_SYMLINKS
        value: "false"
      - name: HELM_SECRETS_VALUES_ALLOW_ABSOLUTE_PATH
        value: "false"
      - name: HELM_SECRETS_VALUES_ALLOW_PATH_TRAVERSAL
        value: "false"
    volumes:
      - name: custom-tools
        emptyDir: {}
    volumeMounts:
      - mountPath: /custom-tools
        name: custom-tools

    initContainers:
      - name: download-tools
        image: alpine:latest
        command: [sh, -ec]
        env:
          - name: HELM_SECRETS_VERSION
            value: "3.12.0"
          - name: SOPS_VERSION
            value: "3.7.2"
          - name: SOPS_ARCH
            value: "linux.arm64"
          - name: KUBECTL_VERSION
            value: "1.22.4"
          - name: KUBECTL_ARCH
            value: "linux/arm64"
        args:
          - |
            mkdir -p /custom-tools/helm-plugins
            wget -qO- https://github.com/jkroepke/helm-secrets/releases/download/v${HELM_SECRETS_VERSION}/helm-secrets.tar.gz | tar -C /custom-tools/helm-plugins -xzf-;

            wget -qO /custom-tools/sops https://github.com/mozilla/sops/releases/download/v${SOPS_VERSION}/sops-v${SOPS_VERSION}.${SOPS_ARCH}
            wget -qO /custom-tools/kubectl https://dl.k8s.io/release/v${KUBECTL_VERSION}/bin/${KUBECTL_ARCH}/kubectl

            chmod +x /custom-tools/*
        volumeMounts:
          - mountPath: /custom-tools
            name: custom-tools
  # helm-secrets (2/2) end
