apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
spec:
  project: infra
  destination:
    name: ""
    namespace: cert-manager
    server: "{{ .Values.spec.destination.server }}"
  source:
    path: ""
    repoURL: "https://charts.jetstack.io"
    targetRevision: v1.8.2
    chart: cert-manager
    helm:
      parameters:
        - name: installCRDs
          value: "true"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
