apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
type: Opaque
stringData:
  # https://cert-manager.io/docs/configuration/acme/dns01/cloudflare
  api-token: "{{ .Values.secrets.CLOUDFLARE_API_TOKEN }}"
